### ISSUE TITLE
RLE8 ist not a true Run Length Encoding

### ISSUE THREAD

**Issue by powturbo** [rainerzufalldererste/hypersonic-rle-kit#6]
RLE8 ist more lz than rle. This is not definition of run length encoding. 
You must compare the speed with similar compression ratio. TurboRLE is compressing better.
In general RLE ist used as preprocessing before entropy coding. RLE8 has worse compression ratio because of the lz similarity and you are not showing a practical usage with true entropy coding like turborc, huffman,....
The entropy coding numbers are also missing for TurboRLE. In this [Benchmark](https://github.com/powturbo/Turbo-Run-Length-Encoding) the results are first sorted by file size and then by speed. The entropy benchmark is showing true EC compression and not any estimation.

**Comment by rainerzufalldererste** [comment]
Hi @powturbo ,
I'm a bit surprised by this statement. I'm not particularly familiar with the exact implementation of lz, but there's no dictionary, hashing or anything similar at play here. However, rle8 consists of a bunch of different codecs so maybe you're talking about something very specific rather than just the entire library in general, but in such generalized terms this is a broad misrepresentation and outright false.

- rle8 Extreme X, rle8 Normal X, rle8 Ultra X are simply straight forward run length encoding implementations with a focus on decoding speed.
- rle8 MMTF is an SIMD [MTF](https://en.wikipedia.org/wiki/Move-to-front_transform)-esque process which may aids compressability by RLE or other compression algorithms and is commonly used in conjunction with such
- rle8 Extreme 8 MMTF 128 facilitates this MMTF transform whilst trying to do integer compression on the MMTFed-non-RLE-able sections
- rle8 SH tries to rle or copy sections but can dynamically substitute commonly occuring symbols that were recently en/decoded with single bits stored in the header in the sections being copied. That's why it's utterly slow but may sometimes produce somewhat decent compression ratios.

The non-RLE codecs aren't particularly central to me, as my main focus was decoding performance. You're welcome to sort or rank or label your benchmarks in whatever way you see fit. I would appreciate if your benchmarks would use an up-to-date version of rle8 to compare against, but I haven't complained so far and am not going to do so going forward. I don't think it's very wise to make statements about one codec being _better_ than another, as this is very situational and heavily depends on the priorities and use-case (i.e. I'm sure you'd feel very misjudged if someone declared rle8 as straight up superior merely based on its license not being copyleft).

All the best,
Chris

**Comment by powturbo** [comment]
Well you can look at the definition a "run length encoding". I've not looked at you recent RLE, but I remember  you are encoding the lengths/offsets in you RLE8 instead of a flag byte  to differenciate the literals with the RLE bytes. 
RLE8 is like lz with offset 1. Hash tables are not needed in this case.
This results in worse compression, especially when combined with entropy coders, a common use case for RLE (for ex. bwt).

- In my benchmarks I'm sorting the entries by the compressed size. We can't claim that something is faster without considering the compression ratio.  The combination with entropy coders is also important. We must also consider Integer-Compression when we are benchmarking with element size other than bytes.

I'll look at the new RLE8 functions when time permits.

Have a nice day

**Comment by rainerzufalldererste** [comment]
Hi @powturbo ,

rle8 Normal and Ultra determine AOT which of the symbols are on average going to benefit from being run length encoded whilst using some trickery to keep the _count_ part of the rle as entropy compression friendly as possible (which is why their encoder is so slow), rle8 Extreme merely parses through the data and when encountering blocks that look run-length-compressible will rle encode them - otherwise it'll copy the entire segment.

When googling the definition, this comes up for me:
> Run-length encoding (RLE) is a lossless compression method where sequences that display redundant data are stored as a single data value representing the repeated block and how many times it appears [...]

which is exactly what all of them do. They don't use variable length symbols or anything. The other newer codecs (SH, Extreme MMTF.) do this as well, but with further complications (as explained above) which may or may not benefit the specific scenario of an application.

If you're unhappy with the way data is presented in my benchmarks or phrased, feel free to publish your own benchmarks and commentary. However, I don't think anything is presented in a misleading or dishonest way. In my humble opinion, people can decide for themselves if the potential tradeoff in compression ratio on their specific data set is worth the gains in terms of decompression speed or potential losses in entropy compressability. Claiming something is outright _better_ or _worse_ without pareto can't be objectively determined, although being _faster_ or _slower_ can be for a specific data set.

All the best,
Chris
